### ISSUE TITLE
BotW - Magnesis/Stasis shader

### ISSUE THREAD

**Issue by Sekkei** [ActualMandM/cemu_graphic_packs#405]
As you have surly noticed as soon as you use e.g the Magnesis ability the 'shader' changes. It's likely this enables or deactivates some effects.
Could someone make this the default behaviour? By the way it fixes the bright bloom in sand and snow areas.

**Comment by Crementif** [comment]
Hm, I've never seen this bright bloom and snow area issue (since you said it got fixed by using e.g. the megnesis ability). Can you please show some screenshots to make it clearer what you think are the issues? And if I'm understanding this correctly, you want a workaround pack that would apply this "fix" from the ability shaders or just a mod that changes the game visually to make it show it always cover the world in an ability's visual effects?

**Comment by ActualMandM** [comment]
No response in over 2 years, closing.
