### ISSUE TITLE
[Xenoblade X] 60fps patch breaks cutscene camera

### ISSUE THREAD

**Issue by ActualMandM** [ActualMandM/cemu_graphic_packs#475]
With Cemu 1.22.0j, I was finally able to try out the 60fps patch at full speed. However, I've noticed major camera bugs with the patch enabled. I've made a video with the patch off and on to showcase the issue.

https://youtu.be/TiZnmgrrcKQ

[Here's the save file for quick access to the cutscene.](https://github.com/slashiee/cemu_graphic_packs/files/5578833/gamedata.zip)

**Comment by lasyan3** [comment]
Yes, this issue is mentionned in the patch:

`0x027398B4 =  lis   r11, _halfRate@ha ; Double updateEventParam cutscene -`
`0x027398C0 =  lfs   f1, _halfRate@l(r11) ;  -`
`0x027A33D8 =  lis   r10, _fullRate@ha ; half SyncFrame cinematic cutscene, fixes timing issues with cinematic cutscenes -`
`0x027A33DC =  lfs   f1, _fullRate@l(r10) ;  but introduces  Shake and stutter issue. CODE XREF: ev::CEvtManager::startPage((float,bool))+6C`

This value is used for **`setPlaySpeed__Q2_2ev13CFrameManagerFf`**

**Comment by Kuiriel** [comment]
I don't suppose there's any way to make it drop to 30FPS whenever cut scenes start because that would require some sort of trigger the code could latch on to?

**Comment by poudink** [comment]
the botw fps++ patch now has something that does exactly that, so I think it should be possible

**Comment by MetrosexualGarbodor** [comment]
Since it has been such a long time and there's no interest, I am offering to PayPal €90 to whoever gets this patch fully working with a 30fps cap during cinematics.
