### ISSUE TITLE
[Breath of the Wild] FPS++ Causing Bad Water Render on 144fps limit @ 3840x2160

### ISSUE THREAD

**Issue by cboscarino** [ActualMandM/cemu_graphic_packs#498]
With the "Graphics" gfx pack Resolution set to "3840x2160 (4K)

If I start a session with FPS++ Limit at 120fps or 144fps Limit, the game renders water wrong. It renders a white cobweb netting look on the top and air-like under water (can see right to the bottom).

If I start a session with FPS++ Limit at 60fps. No problems.

The issue does not happen at 720, 1080, 1440, or 1800 resolutions.

Using nVidia with openGL
![Bad Water](https://user-images.githubusercontent.com/31283902/105440681-04e3eb80-5c35-11eb-808c-9fbe58791867.jpg)

Work around:

If I start at 3840x2160 and with the 60fps limit, I can change it to 144 on the fly and the problem doesn't seem to occur.

The only other time I've seen this issue with the water was when the LOD was set to -2 back with LOD was it's own graphics pack. I am not modifying LOD.

**Comment by Crementif** [comment]
This happens because you disabled Full sync at GX2DrawDone() in Cemu, which is considered a hack. You randomly can get it, but increasing your resolution and/or more FPS can trigger it. Not a problem with the graphic pack itself though. I recommend that you use Vulkan in Cemu, since that performs about as well and has asynchronous shader compilation.
