### ISSUE TITLE
[BOTW] Ultrawide 32:9 UI stretched

### ISSUE THREAD

**Issue by Meridolian** [ActualMandM/cemu_graphic_packs#528]
Hi !

I'm running BOTW on my 32:9 (5120x1440) screen and the game works really great but the UI is really stretched. 
Is it possible to change the UI resolution without changing the game resolution ? Or adapt the UI for ultrawide resolutions ?
Just like in Wind Waker presets:

[Preset]
name = 5120x1440 (32:9)
$width = 5120
$height = 1440
$gameWidth= 1920
$gameHeight= 1080
$lightSource = 2.0
$scaleShader = (1920.0/5120.0)
$aspectRatio = (32.0/9.0)

**Comment by skalfate** [comment]
Hi,

I am going to just reference the reddit thread about this same issue here as well for record keeping, My reply will be the same here as there.

I am once again looking further into this issue and will try to improve hopefully on whatever work I had achieved previously.

I am limited in my knowledge of how it all works but hopefully I gain more progress as the way botw draws its Graphical User Interface, it is harder to work with because it does it through many shaders, while in some smaller games its done through in a single shader.

I will be updating the Aspect Ratio options for selection in the graphic packs window for more variety other than 21/9.

Meanwhile no dates but I do know I will be spending more time on it from today and throughout October.

**Comment by skalfate** [comment]
Hi, posting an update.

An updated version of the pack I had long ago worked on will uploaded here soon, probably today.

**Comment by Meridolian** [comment]
Can't wait to test it ! 
Thank you for your work !

**Comment by skalfate** [comment]
Sorry for the delay. I have been literally doing alot of trial and error to get things right, and getting something right would breka something else. If I need better it would have been easy.

In any case, its not perfect. Its broken in some places while the new version fixes some stuff.

Updates Rules file to give more options.
Allowed for background image to span over the screen in Menus so moving imagery scenes dont clamp.
Fixed Album and Compendium Gallery Menu Screens
Reverted adjustment to Minimap untill we find a way to move over the scissor box through patching.
Runes Menu Fix
Smaller fixes to World Map Screen

[botw_GUI_AR.zip](https://github.com/ActualMandM/cemu_graphic_packs/files/7343139/botw_GUI_AR.zip)

**Comment by Meridolian** [comment]
Hi, sorry didn't see you responded !
I will test it asap ! 

Thanks a lot for your work man

**Comment by Crementif** [comment]
We've recently released [a major update](https://www.reddit.com/r/cemu/comments/rp40r7/a_new_major_breath_of_the_wild_graphic_pack/) to the BotW graphic packs that you can obtain by updating your graphic packs, which included ultrawide HUD, GUI and cutscene fixes, so I'll close this issue.

I do recommend updating to these ultrawide fixes since they're done without shaders but rather assembly patches, which tend to work much better albeit taking more time to develop. See an album of the this version here: https://imgur.com/a/sfbZrRa.
